spring:
  application:
    name: ES
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: 123456

  elasticsearch:
    uris: http://localhost:9200
#    username: root
#    password: 123456

  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456

  session:
    timeout: 2592000
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session

server:
  address: 0.0.0.0
  port: 8765
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

mybatis-plus:
  configuration:
#    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: true
      logic-not-delete-value: false